extends:
  - airbnb
  - prettier

plugins:
  - prettier
  - babel

rules:
  prettier/prettier:
    - error
  import/no-unamed-as-default: 0
  import/prefer-default-export: 0

env:
  browser: true

parser: 'babel-eslint'

settings:
  import/resolver:
    webpack: true
